# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3680f8274b1161aa594b4d3f07bc303fca016ce5750e78288ea54d5b2c7e34d8df71bfb849c880ba3a201ef8ea2c7c31830163ab67fc33e6fc5aae36e41477

test:
  secret_key_base: 5bf1099f7d1609b515ce03f81051ca1f45d91aa1e4b2c8a6376ce43086c73f7fcb0f469b15efd52a0bc2d777c7dff6a122a8e3576ae850ed816f82ced358083e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
